name: Leparaguas
favicon: null
layout_spectrum: 1
typography_spectrum: 0.62699
title: Your Consulting partner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a6978'
    - '#6e9a98'
    - '#103b79'
    - '#a4c1c7'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
