name: Leparaguas
favicon: null
layout_spectrum: 0.84639
typography_spectrum: 0.62699
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a6978'
    - '#6e9a98'
    - '#103b79'
    - '#a4c1c7'
  brandStrength: 0.625
  lightness: 0.05736485938541591
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
