name: Leparaguas
favicon: null
layout_spectrum: 0.6076572760939598
typography_spectrum: 0.687088230624795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.32867798837833107
  lightness: 0.05736485938541591
  saturation: 0.19051334890536964
  rhythmicContrast: 0.13179239607416093
purpose: []
